collector/urls.py
from django.conf.urls import url
from . import views

app_name = "collector"
urlpatterns = [
    # Examples:
    url(r'^$', views.index, name='index'),
    url(r'^list/$', views.list_tweets, name='list'),
    url(r'^load/$', views.upload_file, name='load_tweets'),
    url(r'^load/upload_file$', views.upload_file, name='load_tweets'),
    url(r'^statistics/$', views.tweets_tokenize, name='statistics'),
    url(r'^filter/$', views.filter, name='filter'),
    url(r'^instructions/$', views.instructions, name='instructions'),
    url(r'^tweet/$', views.tweet_for_vote, name='tweet_vote'),
    url(r'^compare/op1:(?P<option1>[^/]+)/op2:(?P<option2>[^/]+)/ev:(?P<event>[^/]+)$', views.compare, name='compare'),
    url(r'^statistics/geo/$', views.geo, name='geo'),
    url(r'^(?P<tweet_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<tweet_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<tweet_id>[0-9]+)/tokenize/$', views.tweet_tokenize, name='tokenize'),
    url(r'^(?P<tweet_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

twitter/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('collector.urls')),
    url(r'^admin/', admin.site.urls),
]

collector/models.py
from django.db import models

# Create your models here.


class TwitterData(models.Model):

    tweet_id = models.CharField(unique=True, max_length=25)
    content = models.CharField(max_length=200)
    lang = models.CharField(null=True, max_length=5, blank=True)
    latitude = models.DecimalField(null=True, max_digits=11,
                                   decimal_places=7, blank=True)
    longitude = models.DecimalField(null=True, max_digits=11,
                                    decimal_places=7, blank=True)
    date = models.DateTimeField(null=True, blank=True)
    tweet_user = models.CharField(max_length=300, null=True)
    user_location = models.CharField(max_length=300, null=True, blank=True)
    tweet_sentiment = models.CharField(max_length=15, null=True, blank=True)

    def __unicode__(self):
        return "Id: " + self.tweet_id + "  Content: " + self.content


class Sentiment(models.Model):

    POSITIVE = 'POS'
    NEGATIVE = 'NEG'
    UNDECIDABLE = 'UND'
    IRRELEVANT = 'IRR'
    VOTE_CHOICES = (
        (POSITIVE, 'Positive'),
        (NEGATIVE, 'Negative'),
        (UNDECIDABLE, 'Undecidable'),
        (IRRELEVANT, 'Irrelevant'),
    )
    sentiment_text = models.CharField(
        max_length=3, choices=VOTE_CHOICES, default=UNDECIDABLE)
    votes = models.IntegerField(default=0)
    tweet = models.ForeignKey(TwitterData, on_delete=models.CASCADE)

    def __unicode__(self):
        return "Id: " + self.tweet.tweet_id + "  Type: " + self.sentiment_text


class TweetFile(models.Model):
    file = models.FileField()

collector/forms.py
from django import forms
from collector.models import TweetFile
from django.forms import ModelForm


class UploadFileForm(ModelForm):
    class Meta:
            model = TweetFile
            fields = ['file']


class FilterForm(forms.Form):
    #Parties
    dp = forms.BooleanField(required=False)
    rp = forms.BooleanField(required=False)

    #Candidates
    dt = forms.BooleanField(required=False)
    hc = forms.BooleanField(required=False)
    mr = forms.BooleanField(required=False)
    bs = forms.BooleanField(required=False)
    tc = forms.BooleanField(required=False)

    #Events
    st = forms.BooleanField(required=False)
    fp = forms.BooleanField(required=False)
    rd = forms.BooleanField(required=False)
    dd = forms.BooleanField(required=False)


class CompareForm(forms.Form):
    #Parties
    options = ["Choice1", "Choice2", "Choice 3"]
    choices_candidates = (
        ('RP', 'Republican Party'),
        ('DP', 'Democratic Party'),
        ('DT', 'Donald Trump'),
        ('HC', 'Hillary Clinton'),
        ('BS', 'Bernie Sanders'),
        ('MR', 'Marco Rubio'),
        ('TC', 'Ted Cruz'),
    )
    choices_dates = (
        ('AA', 'All'),
        ('ST', 'Super Thursday'),
        ('FP', 'Florida Primaries'),
        ('RD', 'Republican Debate'),
        ('DD', 'Democratic Debate'),
    )
    option1 = forms.ChoiceField(choices=choices_candidates)
    option2 = forms.ChoiceField(choices=choices_candidates)
    event = forms.ChoiceField(choices=choices_dates)

class SearchForm(forms.Form):
    text = forms.CharField()
"""
    CHOICES = (
        ('HC', 'Hillary Clinton'),
        ('DT', 'Donald Trump'),
        ('BS', 'Bernie Sanders'),
        ('MR', 'Marco Rubio'),
    )
	#stream.filter(track=["Hillary Clinton", "Donald Trump", "Bernie Sanders", "Marco Rubio", "US election 2016", "Ted Cruz", "John Kasich", "Ben Carson", "Republicans", "Democrats", "Clinton", "Trump", "Bernie", "Rubio", "Cruz", "Carson", "Kasich", "US primaries", "uselections", "Election2016"])
    text= forms.ChoiceField(choices= CHOICES)
"""

collector/views.py
import datetime
import json
import re
import string
import nltk
import sentlex
import sentlex.sentanalysis
import random
from nltk.stem import WordNetLemmatizer
from collections import Counter
from django.shortcuts import render, get_object_or_404
from .models import TwitterData, Sentiment
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from nltk.corpus import stopwords
from nltk.tag import pos_tag
from nltk.probability import ELEProbDist
from nltk import NaiveBayesClassifier
from .forms import UploadFileForm, SearchForm, FilterForm, CompareForm
from django.db.models import Q
from collector.tasks import load_file_task
from pattern.en import singularize
from nvd3 import pieChart
import numpy as np
import matplotlib
import matplotlib.path as path
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Variables
lemmatizer = WordNetLemmatizer()

emoticons_str = r"""
    (?:
        [:=;] # Eyes
        [oO\-]? # Nose (optional)
        [D\)\]\(\]/\\OpP] # Mouth
    )"""


regex_str = [
    emoticons_str,
    r'<[^>]+>',  # HTML tags
    r'(?:@[\w_]+)',  # @-mentions
    r"(?:\#+[\w_]+[\w\'_\-]*[\w_]+)",  # hash-tags
    # URLs
    r'http[s]?://(?:[a-z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-f][0-9a-f]))+',
    r'(?:(?:\d+,?)+(?:\.?\d+)?)',  # numbers
    r"(?:[a-z][a-z'\-_]+[a-z])",  # words with - and '
    r'(?:[\w_]+)',  # other words
    r'(?:\S)'  # anything else
]

positive_vocab = []
negative_vocab = []
tagged_vocab = []

word_features = []

punctuation = list(string.punctuation)
stop = stopwords.words('english') + punctuation + ['rt', 'RT', 'via']


tokens_re = re.compile(
    r'(' + '|'.join(regex_str) + ')', re.VERBOSE | re.IGNORECASE)
emoticon_re = re.compile(
    r'^' + emoticons_str + '$', re.VERBOSE | re.IGNORECASE)


def load_words(file, vector=[]):
    f = open(file, 'r')
    for line in f:
        vector.append(line.split('\n')[0])

load_words("./static/positive-words.txt", positive_vocab)
load_words("./static/negative-words.txt", negative_vocab)
load_words("./static/tagged-words.txt", tagged_vocab)


def index(request):
    return render(request, 'collector/index.html')


def list_tweets(request):
    tweets_list = TwitterData.objects.all()
    context = {'tweets_list': tweets_list}
    return render(request, 'collector/list.html', context)


def function_to_graph(x_axis, y_axis, title):
    chart = pieChart(name=title, color_category='category20c', height=450, width=450)

    xdata = x_axis
    ydata = y_axis

    extra_serie = {"tooltip": {"y_start": "", "y_end": "tweets"}}
    chart.add_serie(y=ydata, x=xdata, extra=extra_serie)
    chart.buildcontent()
    return chart.htmlcontent


def apply_filters(filters):
    filtered_data = Q()
    for t in filters:
        if filters[t]:
            if t == 'rp':
                filtered_data.add(Q(content__icontains="Republican"), Q.OR)
            if t == 'dp':
                filtered_data.add(Q(content__icontains="Democratic"), Q.OR)
            if t == 'dt':
                filtered_data.add(Q(content__icontains="Donald"), Q.OR)
                filtered_data.add(Q(content__icontains="Trump"), Q.OR)
            if t == 'hc':
                filtered_data.add(Q(content__icontains="Hillary"), Q.OR)
                filtered_data.add(Q(content__icontains="Clinton"), Q.OR)
            if t == 'tc':
                filtered_data.add(Q(content__icontains="Ted"), Q.OR)
                filtered_data.add(Q(content__icontains="Cruz"), Q.OR)
            if t == 'bs':
                filtered_data.add(Q(content__icontains="Bernie"), Q.OR)
                filtered_data.add(Q(content__icontains="Sanders"), Q.OR)
            if t == 'mr':
                filtered_data.add(Q(content__icontains="Marco"), Q.OR)
                filtered_data.add(Q(content__icontains="Rubio"), Q.OR)

    tweets_list = TwitterData.objects.filter(filtered_data)
    return tweets_list


def filter(request):
    analysis(TwitterData.objects.all())
    form = FilterForm()
    compare_form = CompareForm()
    file = open("json_data", "r")
    json_data = file.readline()
    context = json.loads(json_data)

    x = context['x_axis_language']
    y = context['y_axis_language']
    graph_languages = function_to_graph(x, y, 'language')

    x1 = context['x_axis_sentiment']
    y1 = context['y_axis_sentiment']
    graph_sentiment = function_to_graph(x1, y1, 'sentiment')

    if request.method == "POST":
        if 'compare' in request.POST:
            compare_form = CompareForm(request.POST)
            if compare_form.is_valid():
                option1 = compare_form.cleaned_data['option1']
                option2 = compare_form.cleaned_data['option2']
                event = compare_form.cleaned_data['event']
                """
                options.setdefault('option1', compare_form.cleaned_data['option1'])
                options.setdefault('option2', compare_form.cleaned_data['option2'])
                options.setdefault('event', compare_form.cleaned_data['event'])
                """
                return HttpResponseRedirect(reverse('collector:compare', args=(option1, option2, event)))
        elif 'filter' in request.POST:
            form = FilterForm(request.POST)
            if form.is_valid():
                # Parties
                filters = {}
                filters.setdefault('rp', form.cleaned_data['rp'])
                filters.setdefault('dp', form.cleaned_data['dp'])
                # Candidates
                filters.setdefault('dt', form.cleaned_data['dt'])
                filters.setdefault('hc', form.cleaned_data['hc'])
                filters.setdefault('tc', form.cleaned_data['tc'])
                filters.setdefault('mr', form.cleaned_data['mr'])
                filters.setdefault('bs', form.cleaned_data['bs'])

                # Events
                filters.setdefault('st', form.cleaned_data['st'])
                filters.setdefault('fp', form.cleaned_data['fp'])
                filters.setdefault('dd', form.cleaned_data['dd'])
                filters.setdefault('rd', form.cleaned_data['rd'])

                #analysis(apply_filters(filters))
                filled_form = FilterForm(request.POST)
                context.update({'form': form , 'filled_form': filled_form, 'compare_form': compare_form, 'graph_languages': graph_languages, 'graph_sentiment': graph_sentiment})
                return render(request, 'collector/filter.html', context)
            else:
                print form.errors
    else:

        filled_form = form
        context.update({'form': form , 'filled_form': filled_form, 'compare_form': compare_form,  'graph_languages': graph_languages, 'graph_sentiment': graph_sentiment})
    return render(request, 'collector/filter.html', context)


def tag_tweets_sentiment():
    tweets_list = TwitterData.objects.all()
    training_set = []
    classify_set = []
    for tweet in tweets_list:
        if tweet.lang == 'en':
            sentiment1 = tag_sentence(nltk.pos_tag(preprocess(tweet.content.lower())))
            sentiment2 = lexicon_tweet(tweet.content.lower())
            if sentiment1 == sentiment2:
                tweet.tweet_sentiment = sentiment1
                tweet.save()
                terms_stop = [term for term in preprocess(tweet.content.lower()) if term not in stop]
                t = (terms_stop, sentiment1)
                training_set.append(t)
            else:
                classify_set.append(tweet)
    bayes_classifier(training_set, classify_set)


def tag_tweet_sentiment(tweet):
    if tweet.lang == 'en':
            sentiment1 = tag_sentence(nltk.pos_tag(preprocess(tweet.content.lower())))
            sentiment2 = lexicon_tweet(tweet.content.lower())
            if sentiment1 == sentiment2:
                tweet.tweet_sentiment = sentiment1
                return tweet.tweet_sentiment
            else:
                return 'not_tagged'
    else:
        return 'no_english'


def analysis(tweets_list):

    count_hash = Counter()
    count_user = Counter()
    count_owner = Counter()

    terms_lang = []
    terms_owner = []
    terms_sentiment = []

    # tag_tweets_sentiment()
    for tweet in tweets_list:
        # Create a list with all the terms
        terms_all = preprocess(tweet.content)

        terms_hash = [term for term in terms_all if term.startswith('#')]
        terms_user = [term for term in terms_all if term.startswith('@')]
        terms_owner.append(tweet.tweet_user)

        if tweet.lang is not None:
            terms_lang.append(tweet.lang)

        if tweet.lang == 'en':
            terms_sentiment.append(tweet.tweet_sentiment)

        count_hash.update(terms_hash)
        count_user.update(terms_user)

    count_owner.update(terms_owner)

    x_lang = list(Counter(terms_lang))
    y_lang = Counter(terms_lang).values()

    x_sent = list(Counter(terms_sentiment))
    y_sent = Counter(terms_sentiment).values()

    context_json = {
                'tweets_number': len(tweets_list),
                'hashtags_number': len(list(count_hash)),
                'users_number': len(list(count_user)),
                'owners_number': len(list(count_owner)),
                'x_axis_language': x_lang,
                'y_axis_language': y_lang,
                'x_axis_sentiment': x_sent,
                'y_axis_sentiment': y_sent,
                'top_hashtags': count_hash.most_common(5),
                'top_users': count_user.most_common(5),
                'top_owners': count_owner.most_common(5),
                }
    file = open("json_data", "w")
    json.dump(context_json, file)


def tag_sentence(sentence, tag_with_lemmas=False):
    total_sentiment = 0
    N = len(sentence)
    i = 0
    while i < N:
        check = sentence[i][0]
        tagged_vocab_words = [j.split('\t')[0] for j in tagged_vocab]
        if sentence[i][0] == 'not' and i != N - 1:
            check = transform(sentence[i + 1][1], sentence[i + 1][0])

collector/templates/collector/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>{% block title %}{% endblock %}</title>

  <!-- CSS  -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'collector/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'collector/css/style.css?version=1.3.1' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.7.0/nv.d3.min.css" rel="stylesheet" />
  <link rel="shortcut icon" type="image/ico" href="{% static 'collector/images/favicon.ico' %}"/>
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
  <script src="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
  <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.7.0/nv.d3.min.js"></script>
  <script src="{% static 'collector/js/wordcloud2.js' %}"></script>
  <style>#map { height: 500px;}
</style>
</head>
<body>
<div class="navbar-fixed">
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'collector:index' %}" class="brand-logo">Twitter Elections</a>
    <ul class="right hide-on-med-and-down">
        {% block navlinks %}{% endblock %}
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="{% url 'collector:statistics' %}">Statistics</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
</div>
  {% block content %}{% endblock %}
  <footer class="page-footer orange">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="{% url 'collector:load_tweets' %}"> Load Tweets</a></li>
            <li><a class="white-text" href="{% url 'collector:filter' %}">Filters</a></li>
            <li><a class="white-text" href="{% url 'collector:list' %}">List</a></li>
            <li><a class="white-text" href="{% url 'collector:instructions' %}">Vote Tweets</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'collector/js/materialize.js' %}"></script>
  <script src="{% static 'collector/js/init.js?version=1.0.2' %}"></script>

  </body>
</html>

collector/templates/collector/bayes.html
{% extends "collector/base.html" %}
{% block title %}Twitter Elections{% endblock %}
{% block content %}
	{% for tweet in tweets_list%}
		<p>{{ tweet}}</p>
	{% endfor %}
	<p>{{ word_features }}</p>
	<p>{{ training_set }}</p>
{% endblock %}

collector/templates/collector/compare.html
{% extends "collector/base.html" %}
{% load staticfiles%}
{% block title %}Twitter Elections{% endblock %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col s6 red white-text center">
				<h2> Option 1 </h2>
				<img class="circle responsive-img compare-img" src="{% static 'collector/images/DemocraticLogo.png' %}" alt="Contact Person">
				<h3>{{OP1_tweets_number}} Tweets</h3>
				<p> {{OP1_hashtags_number}} Hashtags</p>
				<p> {{OP1_users_number}} Mentions </p>
				<p> {{OP1_owners_number}} Users </p>
			</div>
			<div class="col s6 blue white-text center">
				<h2> Option 2 </h2>
				<img class="circle responsive-img compare-img" src="{% static 'collector/images/DemocraticLogo.png' %}" alt="Contact Person">
				<h3>{{OP2_tweets_number}} Tweets</h3>
				<p> {{OP2_hashtags_number}} Hashtags</p>
				<p> {{OP2_users_number}} Mentions </p>
				<p> {{OP2_owners_number}} Users </p>
			</div>
		</div>
	</div>
{% endblock %}

collector/templates/collector/detail.html
{% extends "collector/base.html" %}
{% block title %}Twitter Elections{% endblock %}
{% block content %}

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

      <div class="row">
        <div class="col s12">
          <div class="card ">
            <div class="card-content">
              <span class="card-title blue-text">Tweet {{sentiment}}:</span>
              <p>{{ tweet.content }}</p>
            </div>
            <div class="card-action">
              <a class="blue-text" href="{% url 'collector:tokenize' tweet.id %}"> Analytics </a>
            </div>
          </div>
        </div>
      </div>

    <p class="text">How is the sentiment stated in the previous tweet?</p>

	      <ul class="collapsible" data-collapsible="accordion">
		    <li>
		      <div class="collapsible-header green white-text"><i class="material-icons">sentiment_satisfied</i>Positive</div>
		      <div class="collapsible-body "><p>A positive sentiment is ...</p></div>
		    </li>
		    <li>
		      <div class="collapsible-header red white-text"><i class="material-icons">sentiment_dissatisfied</i>Negative</div>
		      <div class="collapsible-body"><p>A negative sentiment is ...</p></div>
		    </li>
		    <li>
		      <div class="collapsible-header grey white-text"><i class="material-icons">sentiment_neutral</i>I can't decide</div>
		      <div class="collapsible-body"><p>...</p></div>
		    </li>
		    <li>
		      <div class="collapsible-header teal white-text"><i class="material-icons">sentiment_very_dissatisfied</i>Irrelevant</div>
		      <div class="collapsible-body"><p>An irrelevant tweet is ...</p></div>
		    </li>
	  	</ul>

	<form action="{% url 'collector:vote' tweet.id %}" method="post">
	{% csrf_token %}
	<div class="row">

	{% for choice in tweet.sentiment_set.all %}
	<div class="col s12 m3 ">
		{% if choice.sentiment_text = 'POS'%}

			<button class="btn waves-effect waves-light green" id="choice{{ forloop.counter }}" value="{{ choice.id }}" type="input" name="choice"><i class="material-icons left">sentiment_satisfied</i>Positive</button>
		{% elif choice.sentiment_text = 'NEG'%}

			<button class="btn waves-effect waves-light red" id="choice{{ forloop.counter }}" value="{{ choice.id }}" type="input" name="choice"><i class="material-icons left">sentiment_dissatisfied</i>Negative</button>
		{% elif choice.sentiment_text = 'UND'%}

			<button class="btn waves-effect waves-light grey" id="choice{{ forloop.counter }}" value="{{ choice.id }}" type="input" name="choice"><i class="material-icons left">sentiment_neutral</i>I can't decide</button>
		{% elif choice.sentiment_text = 'IRR'%}
			<button class="btn waves-effect waves-light" id="choice{{ forloop.counter }}" value="{{ choice.id }}" type="input" name="choice"><i class="material-icons left">sentiment_very_dissatisfied</i>Irrelevant</button>
		{% endif %}
	</div>
	{% endfor %}
	</div>
	</form>

{% endblock %}

collector/templates/collector/list.html
{% extends "collector/base.html" %}
{% block title %}Twitter Elections{% endblock %}
{% block content %}

	{% if tweets_list %}
	    <ul>
	    {% for tweet in tweets_list %}
	        <li><a href="{% url 'collector:detail' tweet.id %}">{{ tweet.content }}</a></li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>No tweets are now available.</p>
	{% endif %}
{% endblock %}

collector/templates/collector/results.html
{% extends "collector/base.html" %}
{% block title %}Twitter Elections{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
			<div class="col s12">

			          <div class="card">
				            <div class="card-content">
				              <span class="card-title blue-text">Tweet:</span>
				              <p>{{ tweet.content }}</p>
				            </div>
			          </div>

			</div>
		</div>

		<ul>
		{% for choice in tweet.sentiment_set.all %}
		    <li>{{ choice.sentiment_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
		{% endfor %}
		</ul>

	<a class="btn" href="{% url 'collector:tweet_vote'%}">Vote again?</a>
</div>
{% endblock %}

collector/templates/collector/upload.html
{% extends 'collector/base.html' %}

{% block content %}
		
		<p> Number of loaded tweets {{number}} </p>

        <p>Add more: </p>

		{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}

        <form method="POST" action="upload_file"  class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Load</button>
        </form>

{% endblock %}

collector/templates/collector/vote.html
{% extends "collector/base.html" %}
{% block title %}Twitter Elections{% endblock %}
{% block content %}
<div class="container">
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

      <div class="row">
        <div class="col s12">
          <div class="card ">
            <div class="card-content">
              <span class="card-title blue-text">Tweet {{sentiment}}:</span>
              <p>{{ tweet.content }}</p>
            </div>
          </div>
        </div>
      </div>

	<form action="{% url 'collector:vote' tweet.id %}" method="post">
	{% csrf_token %}
	<div class="row">

	{% for choice in tweet.sentiment_set.all %}
	<div class="col s12 m3 ">
		{% if choice.sentiment_text = 'POS'%}

			<button class="btn waves-effect waves-light green" id="choice{{ forloop.counter }}" value="{{ choice.id }}" type="input" name="choice"><i class="material-icons left">sentiment_satisfied</i>Positive</button>
		{% elif choice.sentiment_text = 'NEG'%}

			<button class="btn waves-effect waves-light red" id="choice{{ forloop.counter }}" value="{{ choice.id }}" type="input" name="choice"><i class="material-icons left">sentiment_dissatisfied</i>Negative</button>
		{% elif choice.sentiment_text = 'UND'%}

			<button class="btn waves-effect waves-light grey" id="choice{{ forloop.counter }}" value="{{ choice.id }}" type="input" name="choice"><i class="material-icons left">sentiment_neutral</i>I can't decide</button>
		{% elif choice.sentiment_text = 'IRR'%}
			<button class="btn waves-effect waves-light" id="choice{{ forloop.counter }}" value="{{ choice.id }}" type="input" name="choice"><i class="material-icons left">sentiment_very_dissatisfied</i>Irrelevant</button>
		{% endif %}
	</div>
	{% endfor %}
	</div>
	</form>
</div>
{% endblock %}